<?php

namespace app\modules\property\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "prop_group".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $class
 */
class Group extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prop_group';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'alias', 'class'], 'string', 'max' => 255],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                'ensureUnique' => true,
                'slugAttribute' => 'alias',
            ],
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('property', 'ID'),
            'name' => Yii::t('property', 'Name'),
            'alias' => Yii::t('property', 'Alias'),
            'class' => Yii::t('property', 'Class'),
        ];
    }

    public function getList($class){
        $model = static::find()->where(['class' => $class])->all();
        return [0 => ''] + ArrayHelper::map($model, 'id' , 'name');
    }
}
