<?php

namespace app\modules\admin;

use app\modules\admin\rbac\Rbac;
use yii\filters\AccessControl;
use Yii;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\admin\controllers';

    public $defaultRoute = 'assignment';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [Rbac::PERMISSION_ADMIN_PANEL],
                    ],
                ],
            ],
        ];
    }

    public function init()
    {
        //\Yii::$app->language = 'ru-RU';
        if(\Yii::$app->language !== 'ru-RU'){

            \Yii::$app->urlManager->redirectToLanguage('ru');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function t($category, $message, $params = [], $language = null)
    {
        return Yii::t('modules/admin/' . $category, $message, $params, $language);
    }
}
